mutation(
	$authors: [ID!]
	$commentable: Boolean
	$excerpt: String
	$featured: Boolean
	$html: String
	$id: ID!
	$image: String
	$metaTitle: String
	$metaDescription: String
	$markdown: String
	$primaryAuthorId: ID
	$publishedBy: ID
	$publishedAt: Date
	$paged: Boolean
	$slug: String
	$status: String
	$tags: [ID!]
	$title: String
) {
	updatePost(
		authors: $authors
		commentable: $commentable
		excerpt: $excerpt
		featured: $featured
		html: $html
		id: $id
		image: $image
		metaTitle: $metaTitle
		metaDescription: $metaDescription
		markdown: $markdown
		primaryAuthorId: $primaryAuthorId
		publishedBy: $publishedBy
		publishedAt: $publishedAt
		paged: $paged
		slug: $slug
		status: $status
		tags: $tags
		title: $title
	) {
		id
	}
}
